services:
  - type: web
    name: manualcrms
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      chmod +x deploy.sh
      ./deploy.sh
    startCommand: |
      chmod +x start.sh
      ./start.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://manualcrms.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: warning
      - key: QUEUE_CONNECTION
        value: sync
      - key: NODE_ENV
        value: production
